- hosts: webservers
  remote_user: raynor
  vars:
    home: /home/raynor/mm
    user: raynor
    frontend_repo: Arcee
    backend_repo: OptimusPrime
    ai_repo: Unicron
  
  tasks:
    - name: Create mm folder
      file:
        path: '{{ home }}'
        state: directory
        owner: '{{ user }}'
        group: '{{ user }}'
        
    - name: Clone Arcee (frontend)
      git:
        accept_newhostkey: true
        repo: 'git@github.com:Mockmentor/Arcee.git'
        dest: '{{ home }}/{{ frontend_repo }}'

    - name: Install docker and docker-compose
      block:
        - name: Install required system packages
          become: yes
          apt:
            pkg:
              - apt-transport-https
              - ca-certificates
              - curl
              - software-properties-common
              - python3-pip
              - virtualenv
              - python3-setuptools
            state: latest
            update_cache: true

        - name: Add Docker GPG apt Key
          become: yes
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker Repository
          become: yes
          apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu jammy stable
            state: present

        - name: Update apt and install docker-ce
          become: yes
          apt:
            name: 
              - docker-ce
              - docker-ce-cli
              - containerd.io
              - docker-buildx-plugin
              - docker-compose-plugin
            state: latest
            update_cache: true

        - name: Install Docker Module for Python
          become: yes
          pip:
            name: docker

        - name: Add user to Docker group
          become: yes
          user:
            name: raynor
            append: yes
            groups: docker

    - name: Clone Optimus (backend)
      git:
        accept_newhostkey: true
        repo: 'git@github.com:Mockmentor/OptimusPrime.git'
        dest: '{{ home }}/{{ backend_repo }}'

    - name: Clone Unicron (ai model)
      git:
        accept_newhostkey: true
        repo: 'git@github.com:Mockmentor/Unicron.git'
        dest: '{{ home }}/{{ ai_repo }}'

    # - name: Run server
    #   command:
    #     chdir: '{{ home }}/{{ frontend_repo }}'
    #     cmd: make start
